#!/bin/bash

eval "$(conda shell.bash hook)"
conda activate VTL

# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd_contrast.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd_DANN_after_ld_contrast.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd_DANN_after_ld_dp_contrast.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd_DANN_after_ld_dp.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd_DANN_after_ld.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_wd_contrast.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_wd_DANN_after_ld_contrast.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_wd_DANN_after_ld_dp_contrast.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_wd_DANN_after_ld_dp.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_wd_DANN_after_ld.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_wd.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_lr_wd_contrast.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_lr_wd_DANN_after_ld_contrast.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_lr_wd_DANN_after_ld_dp_contrast.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_lr_wd_DANN_after_ld_dp.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_lr_wd_DANN_after_ld.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_lr_wd.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_wd_contrast.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_wd_DANN_after_ld_contrast.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_wd_DANN_after_ld_dp_contrast.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_wd_DANN_after_ld_dp.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_wd_DANN_after_ld.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_wd.sbatch

# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd_contrast_extended.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd_DANN_after_ld_contrast_extended.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd_DANN_after_ld_dp_contrast_extended.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_wd_contrast_extended.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_lr_wd_DANN_after_ld_contrast_extended.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_lr_wd_DANN_after_ld_dp_contrast_extended.sbatch

# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd_contrast_extended_100.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd_DANN_after_ld_contrast_extended_100.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd_DANN_after_ld_dp_contrast_extended_100.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_wd_contrast_extended_100.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_wd_DANN_after_ld_contrast_extended_100.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_wd_DANN_after_ld_dp_contrast_extended_100.sbatch

# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd_extended_100.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd_DANN_after_ld_extended_100.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd_DANN_after_ld_dp_extended_100.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_wd_extended_100.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_wd_DANN_after_ld_extended_100.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_wd_DANN_after_ld_dp_extended_100.sbatch

# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd_DANN_after_ld_dp_extended.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd_DANN_after_ld_extended.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_bn_lr_wd_extended.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_wd_DANN_after_ld_extended.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_wd_extended.sbatch
# sbatch scripts/train_bing_thermal_partial_conv4096_resnet50_bn_wd_DANN_after_ld_dp_extended.sbatch

# sbatch scripts/train_bing_thermal_translation_10_noncontrast.sbatch
# sbatch scripts/train_bing_thermal_translation_10.sbatch
# sbatch scripts/train_bing_thermal_translation_100_noncontrast.sbatch
# sbatch scripts/train_bing_thermal_translation_100.sbatch



